### ISSUE TITLE
[BUG] anchor element does not close the tooltip on click

### ISSUE THREAD

**Issue by danny-does-stuff** [ReactTooltip/react-tooltip#1180]
**Bug description**
When using the `openOnClick` prop, clicking on the anchor element opens the tooltip, but clicking the button does _not_ close the tooltip.

**Version of Package**
v5.26.3

**To Reproduce**
Create `button` as the anchor element, followed by a `<Tooltip>` with the prop `openOnClick`

**Expected behavior**
When the tooltip can be opened by clicking on the anchor element, I would expect to be able to close the tooltip by clicking the anchor element as well. I would still want to be able to close the tooltip by clicking anywhere else on the screen as well.

**Desktop:**
 - OS: MacOS
 - Browser: Arc (chromium)
 - Version: 1.36.0 (latest)
 - Frameworks React 18 (create-react-app)

**Additional context**
I got the same behavior by using different variations of `openEvents` and `closeEvents`. I could not get the desired behavior

**Comment by danny-does-stuff** [comment]
Resolved! The main problem was that my button only had an SVG icon inside. It works fine if the child of the button is just some text. I don't know whether there's anything react-tooltip can do to fix that. To get this to work, you have to use the props `openOnClick` and `closeEvents={{ click: true }}`. Here is a [code sandbox](https://codesandbox.io/p/sandbox/react-tooltip-hide-on-click-m8q7lt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clubs1qac00063b8fam86cubg%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clubs1qab00023b8fdtuilnsg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clubs1qab00033b8f5ncn38io%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clubs1qac00053b8fgn45uonu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clubs1qab00023b8fdtuilnsg%2522%253A%257B%2522id%2522%253A%2522clubs1qab00023b8fdtuilnsg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clubs1qac00053b8fgn45uonu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clubs1qac00043b8fy7vmrt3t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clubs1qac00053b8fgn45uonu%2522%252C%2522activeTabId%2522%253A%2522clubs1qac00043b8fy7vmrt3t%2522%257D%252C%2522clubs1qab00033b8f5ncn38io%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clubs1qab00033b8f5ncn38io%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by gabrieljablonski** [comment]
The intended behavior for `openOnClick` is for it to just *open* on click. When using just that prop, the tooltip will only close when clicking outside the anchor.

The correct way to achieve the behavior you want, as you've pointed out, is to use `openEvents={{ click: true }}` (or simply `openOnClick`) alongside `closeEvents={{ click: true }}`.

This behavior for the `openOnClick` might be a little misleading, so we'll consider updating the docs to explain that.

Now for the behavior with an SVG, we'll take a look at it later and see if there's anything viable we can do directly with the tooltip.

**Comment by gabrieljablonski** [comment]
Apparently it's a known issue with using SVGs.

c7f865f398a4045de631d48722698987ac6ec2db adds a section on the troubleshooting page about it. Should be live on the docs soon.

**Comment by rodrigofsouto** [comment]
I think it's more than that... it seems the click event is not propagating to the tooltip container.

Here is my Tooltip definition:


```
<Tooltip openEvents={{focus:true, mouseenter:true}} 
      closeEvents={{blur:true, mouseleave:true, click:true}} 
      id='mytt'/>

```
If I have a <MyButton /> component that returns something like this:

```
<div id='wrapper' data-tooltip-id='mytt' data-tooltip-content='testing...'>  
  <button id='button' type='button'>
    <span id='text'>Click here!</span>
  </button>
</div>
```

The click event on the MyButton component does not close the tooltip. Even if I add data-tooltip-id and data-tooltip-content to the button element, it still doesn't work. It only works if I add them to the text element.

**Comment by ru13r** [comment]
> Apparently it's a known issue with using SVGs.
> 
> [c7f865f](https://github.com/ReactTooltip/react-tooltip/commit/c7f865f398a4045de631d48722698987ac6ec2db) adds a section on the troubleshooting page about it. Should be live on the docs soon.

Had exactly the same setup with SVG icons. 
Can we add up the link to this troubleshooting section in the events section of docs? It is not quite obvious.
